version: "3.7"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27018

  db-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: db
  # rabbitmq:
  #   image: rabbitmq:3.6.6-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672